//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestStand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyFileBaseName = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYFILEBASENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILEBASENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyFileName     = {0}{1}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYFILENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyGuidString   = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBLYGUIDSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYGUIDSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssembyDirName       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_ASSEMBYDIRNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBYDIRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Comments             = {0}{1}.
        /// </summary>
        internal static string MSG_ASM_PROPS_COMMENTS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     CompanyName          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_COMPANYNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Culture              = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_CULTURE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Description          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     File Creation Date   = {0} ({1} UTC).
        /// </summary>
        internal static string MSG_ASM_PROPS_FILE_CREATION_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_CREATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     File Modified Date   = {0} ({1} UTC).
        /// </summary>
        internal static string MSG_ASM_PROPS_FILE_MODIFIED_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     LegalCopyright       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_LEGALCOPYRIGHT {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALCOPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     LegalTrademarks      = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_LEGALTRADEMARKS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALTRADEMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ProductName          = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_PRODUCTNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     PublicKeyToken       = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_PUBLICKEYTOKEN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PUBLICKEYTOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Runtime Version      = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_RUNTIME_VERSION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_RUNTIME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected properties of the library under test:{0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of selected properties{0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_END {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     VersionString        = {0}.
        /// </summary>
        internal static string MSG_ASM_PROPS_VERSIONSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_VERSIONSTRING", resourceCulture);
            }
        }
    }
}
