//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeHandle = {0}, Subscript = {1}.
        /// </summary>
        internal static string BCLI_INDEX_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("BCLI_INDEX_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCLType = {0}, MaximumDecimalDigits = {1}, RequiredStorageBytes = {2}, CapacityInBits = {3}, IsSigned = {4}, GUIDPerType = {5}.
        /// </summary>
        internal static string BCLI_TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("BCLI_TOSTRING_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    6         5         4         3         2         1          .
        /// </summary>
        internal static string BIT_RULER_TENS_HIGHTOLOW {
            get {
                return ResourceManager.GetString("BIT_RULER_TENS_HIGHTOLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           1         2         3         4         5         6   .
        /// </summary>
        internal static string BIT_RULER_TENS_LOWTOHIGH {
            get {
                return ResourceManager.GetString("BIT_RULER_TENS_LOWTOHIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3210987654321098765432109876543210987654321098765432109876543210.
        /// </summary>
        internal static string BIT_RULER_UNITS_HIGHTOLOW {
            get {
                return ResourceManager.GetString("BIT_RULER_UNITS_HIGHTOLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789012345678901234567890123456789012345678901234567890123.
        /// </summary>
        internal static string BIT_RULER_UNITS_LOW2HIGH {
            get {
                return ResourceManager.GetString("BIT_RULER_UNITS_LOW2HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero AND divisible by 8..
        /// </summary>
        internal static string ERRMSG_BIT_COUNT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERRMSG_BIT_COUNT_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value most be greater than or equal to zero..
        /// </summary>
        internal static string ERRMSG_BIT_GROUPS_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("ERRMSG_BIT_GROUPS_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bits per Group value must be numeric. The specified value is {1}{0}{1}..
        /// </summary>
        internal static string ERRMSG_BIT_GROUPSIZE_MUST_BE_NUMERIC {
            get {
                return ResourceManager.GetString("ERRMSG_BIT_GROUPSIZE_MUST_BE_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bits per Group value must be greater than zero..
        /// </summary>
        internal static string ERRMSG_BIT_GROUPSIZE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERRMSG_BIT_GROUPSIZE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An FormatException exception was caught in the Format method on an instance of the BitMaskFormat class.{2}    Format String    = {0}{2}Object to Format = {1}.
        /// </summary>
        internal static string ERRMSG_ENRICED_FORMAT_EXCEPTION {
            get {
                return ResourceManager.GetString("ERRMSG_ENRICED_FORMAT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bits per Group value must be evenly divisible by {0}. The specified value was {1}..
        /// </summary>
        internal static string ERRMSG_INVALID_BIT_GROUPSIZE {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_BIT_GROUPSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in WizardWrx.BitHelpers.FormatBitMask: internal variable fpFormattingParams.FormatPrefix in invalid. The actual value is {0}..
        /// </summary>
        internal static string ERRMSG_INVALID_FORMAT_PREFIX_ENUM {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_FORMAT_PREFIX_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ruler string length is incorrect.{2}    Expected length = {0}{2}    Actual length   = {1}.
        /// </summary>
        internal static string ERRMSG_INVALID_RULER_STRING {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_RULER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only integeral types are supported..
        /// </summary>
        internal static string ERRMSG_TYPE_MUST_BE_INTEGERAL {
            get {
                return ResourceManager.GetString("ERRMSG_TYPE_MUST_BE_INTEGERAL", resourceCulture);
            }
        }
    }
}
